# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cities_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('lat_long', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mintempm', models.FloatField()),
                ('maxtempm', models.FloatField()),
                ('mindewptm', models.FloatField()),
                ('maxdewptm', models.FloatField()),
                ('minhumidity', models.FloatField()),
                ('maxhumidity', models.FloatField()),
                ('minwspdm', models.FloatField()),
                ('maxwspdm', models.FloatField()),
                ('minvism', models.FloatField()),
                ('maxvism', models.FloatField()),
                ('minpressurem', models.FloatField()),
                ('maxpressurem', models.FloatField()),
                ('weather_date', models.DateField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.Cities_available')),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.Cities_available'),
        ),
    ]
