# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:18
from __future__ import unicode_literals

from django.db import migrations


def load_stores_from_sql():
    from weather_data.settings import BASE_DIR
    import os
    sql_statements = open(os.path.join(BASE_DIR,'weather/sql/available_cites.sql'), 'r').read()
    return sql_statements

class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(load_stores_from_sql()),
    ]
